version: '3.8'

services:
  eureka-service:
    build:
      context: ./eureka-service
    container_name: eureka-service
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    networks:
      - spring-net

  identity-database:
    image: postgres:15
    container_name: identity-database
    environment:
      POSTGRES_DB: identity_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - spring-net

  identity-service:
    build:
      context: ./identity-service
    container_name: identity-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://identity-database:5432/identity_database
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
    depends_on:
      - identity-database
      - eureka-service
    networks:
      - spring-net

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
    depends_on:
      - eureka-service
    networks:
      - spring-net

networks:
  spring-net:
    driver: bridge