server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: lb://identity-service
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2

        - id: profile_service
          uri: lb://profile-service
          predicates:
            - Path=${app.api-prefix}/profile/**
          filters:
            - StripPrefix=2

        - id: notification_service
          uri: lb://notification-service
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2

        - id: post_service
          uri: lb://post_service
          predicates:
            - Path=${app.api-prefix}/post/**
          filters:
            - StripPrefix=2

        - id: file_service
          uri: lb://file_service
          predicates:
            - Path=${app.api-prefix}/file/**
          filters:
            - StripPrefix=2

        - id: chat_service
          uri: lb://chat_service
          predicates:
            - Path=${app.api-prefix}/chat/**
          filters:
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true