server:
  port: 8081
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:mysql://localhost:3306/identity_database
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 226293715494-2r9hc1jvefvvprcae3h5irv722a5ve5h.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:3000/auth/google/callback
          facebook:
            client-id: 375135140938503
            client-secret: 4427eb0b6485e787867616edd62aeea6
            redirect-uri: http://localhost:3000/auth/facebook/callback

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

jwt:
  signerKey: "LKKTHMuc3PmdHcoIfzz33X46iHe5NXFZZFtSHBO6p2FNLaJr9DxCHLDYJpMSRgsO7KDEyDEiQb9RPzpWHeqVqNaqE17/KGEUiMqTnn27OVN52N+THKMlf8pn03FbRsgjladcayhNVkplmsT6NxdGpQ6VFLdLJH7zeX79HKzp/YGzSJ2pk7FSz/ykhHAju8q5"
  refreshKey: "WVwKgDLkTuwdNfnl0/Q7xYEByJE00zyfrxXt2xs1ezXqUgoplZbinHVuXT889uSKY0spy4leKQo5W2lIXYk8F7qlLscpesicDFwVx70j2b0dFY7CCUwD6dv6VsLMUA7GgX3vfEHi3kFNJOyHX1lvTbEGxVa051rFbHEKA18F+MjjfGybo2xtnausJ4ADuC8N"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

app:
  services:
    profile: http://localhost:8081/profile